# Generated by Django 5.1.5 on 2025-06-19 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebornApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('settings_updated', 'Settings Updated'), ('maintenance_enabled', 'Maintenance Enabled'), ('maintenance_disabled', 'Maintenance Disabled'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('item_approved', 'Item Approved'), ('item_rejected', 'Item Rejected'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('system_event', 'System Event')], max_length=50)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Reborn Thriftshop', help_text='Name of your thrift shop', max_length=100)),
                ('site_description', models.TextField(default='Your premier online thrift store for quality second-hand items', help_text='Brief description of your site')),
                ('site_logo', models.ImageField(blank=True, help_text='Site logo (recommended: 200x60px)', null=True, upload_to='site/')),
                ('contact_email', models.EmailField(default='admin@rebornthrift.com', help_text='Main contact email for the site', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('contact_address', models.TextField(blank=True, help_text='Physical address (optional)')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable to make site unavailable to public')),
                ('maintenance_message', models.TextField(default="We're currently performing maintenance to improve your experience. Please check back soon!", help_text='Message displayed during maintenance')),
                ('maintenance_start_time', models.DateTimeField(blank=True, help_text='When maintenance mode was enabled', null=True)),
                ('maintenance_estimated_end', models.DateTimeField(blank=True, help_text='Estimated end time for maintenance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last admin who updated settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
