# Generated by Django 5.2 on 2025-05-07 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebornApp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rebornApp.category'),
        ),
        migrations.AddField(
            model_name='seller',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
